# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [1]:
import numpy as np

In [3]:
# Exercise 1
arr1 = np.arange(1, 11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]



---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [5]:
# Exercise 2
arr2 = np.zeros((3, 3))
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [7]:
# Exercise 3
arr3 = np.linspace(0, 5, 10)
print(arr3)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]



---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [9]:
# Exercise 4
arr4 = np.eye(5)
print(arr4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [13]:
# Exercise 5
arr5 = np.random.rand(4, 4)
print(arr5)

[[0.10717458 0.11614486 0.46591129 0.659419  ]
 [0.37727047 0.1651458  0.2618158  0.10041367]
 [0.47531938 0.52312524 0.4001124  0.65318444]
 [0.28813644 0.97689869 0.65520913 0.08186399]]



---

### Exercise 6:
Find the shape of a NumPy array.


In [15]:
# Exercise 6
print( arr5.shape)

(4, 4)



---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [17]:
# Exercise 7
arr7 = np.arange(16).reshape(4, 4)
print(arr7)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [19]:
# Exercise 8
print(arr7.dtype)

int32



---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [21]:
# Exercise 9
arr9 = np.arange(1, 101)
even_numbers = arr9[arr9 % 2 == 0]
print(even_numbers)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]



---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [25]:
# Exercise 10
arr10 = np.random.randint(10, 51, size=(6, 6))
print(arr10)

[[25 25 22 38 47 22]
 [27 35 50 24 42 38]
 [50 13 12 37 42 41]
 [30 44 44 17 38 35]
 [40 42 31 47 19 26]
 [19 24 14 31 26 35]]



---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [27]:
# Exercise 11
matrix = np.arange(1, 17).reshape(4, 4)
submatrix = matrix[1:3, 1:3]
print(submatrix)

[[ 6  7]
 [10 11]]



---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [29]:
# Exercise 12
arr12 = np.array([1, 2, 3, 4])
print(arr12.sum())

10



---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [33]:
# Exercise 13
arr13 = np.array([1, 2, 3, 4, 5])
print("Mean =", arr13.mean())
print("Median =", np.median(arr13))
print("Standard Deviation =", arr13.std())

Mean = 3.0
Median = 3.0
Standard Deviation = 1.4142135623730951



---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [35]:
# Exercise 14
arr14 = np.array([10, 20, 5, 8])
print("Max =", arr14.max())
print("Min =", arr14.min())

Max = 20
Min = 5



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [37]:
# Exercise 15
arr15 = np.random.randint(1, 100, 20)
print("Array =", arr15)
print("Index of max value:", np.argmax(arr15))

Array = [70 89 54 55 11 29 27 66 20 19 25 37 81 77 33 89 21 66 99 48]
Index of max value: 18



---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [39]:
# Exercise 16
arr16 = np.array([1, 2, 3, 4, 5])
reversed_arr = arr16[::-1]
print(reversed_arr)

[5 4 3 2 1]



---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [41]:
# Exercise 17
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
result = a * b
print(result)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]



---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [47]:
# Exercise 18
arr18 = np.array([1, 2, 3, 4])
diag_matrix = np.diag(arr18)
print(diag_matrix)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]



---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [49]:
# Exercise 19
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
product = np.dot(x, y)
print(product)

[[19 22]
 [43 50]]



---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [55]:
# Exercise 20
arr20 = np.array([[1, 2], [3, 4]])
flat = arr20.flatten()
print(flat)

[1 2 3 4]



---

### Exercise 21:
Stack two NumPy arrays vertically.


In [57]:
# Exercise 21
a21 = np.array([1, 2, 3])
b21 = np.array([4, 5, 6])
vertical_stack = np.vstack((a21, b21))
print(vertical_stack)

[[1 2 3]
 [4 5 6]]



---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [59]:
# Exercise 22
a22 = np.array([1, 2, 3])
b22 = np.array([4, 5, 6])
horizontal_stack = np.hstack((a22, b22))
print(horizontal_stack)

[1 2 3 4 5 6]



---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [67]:
# Exercise 23
a23 = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.split(a23, 3)
print(split_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]



---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [71]:
# Exercise 24
a24 = np.random.rand(3, 3)
rounded = np.round(a24, 2)
print(rounded)

[[0.76 0.87 0.42]
 [0.1  0.53 0.19]
 [0.99 0.19 0.97]]



---

### Exercise 25:
Find the unique elements of a NumPy array.


In [73]:
# Exercise 25
a25 = np.array([1, 2, 2, 3, 4, 4, 5])
unique_elements = np.unique(a25)
print(unique_elements)

[1 2 3 4 5]



---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [75]:
# Exercise 26
a26 = np.array([1, 5, 3, 10, 2])
a26[a26 < 4] = 4
print(a26)

[ 4  5  4 10  4]



---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [77]:
# Exercise 27
a27 = np.array([1, 2, 3, 4])
cumsum = np.cumsum(a27)
print(cumsum)

[ 1  3  6 10]



---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [79]:
# Exercise 28
a28 = np.array([0, 1, 2, 0, 3, 0])
non_zero_count = np.count_nonzero(a28)
print(non_zero_count)

3



---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [87]:
# Exercise 29
ar29 = np.random.randint(1, 100, 10)
sorted_arr = np.sort(ar29)
print("Original:", ar29)
print("Sorted:", sorted_arr)

Original: [85 40 24 81 38 10 46  4 62 43]
Sorted: [ 4 10 24 38 40 43 46 62 81 85]



---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [91]:
# Exercise 30
a30 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_sum = a30.sum(axis=1)
col_sum = a30.sum(axis=0)
print("Row-wise sum:", row_sum)
print("Column-wise sum:", col_sum)

Row-wise sum: [ 6 15 24]
Column-wise sum: [12 15 18]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [93]:
# Exercise 31
a31 = np.random.rand(3, 3) * 100
normalized = (a31 - np.min(a31)) / (np.max(a31) - np.min(a31))
print(normalized)

[[0.66498469 1.         0.71233032]
 [0.60665955 0.28534274 0.89492546]
 [0.59628702 0.         0.58382453]]



---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [95]:
# Exercise 32
a32 = np.array([1, 2, 3])
b32 = np.array([4, 5, 6])
dot_product = np.dot(a32, b32)
print("Dot Product:", dot_product)

Dot Product: 32



---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [97]:
# Exercise 33
a33 = np.array([[1, 2], [3, 4]])
trace = np.trace(a33)
print("Trace:", trace)

Trace: 5



---

### Exercise 34:
Create a 2D array and swap two rows.


In [99]:
# Exercise 34
a34 = np.array([[1, 2], [3, 4]])
a34[[0, 1]] = a34[[1, 0]]
print(a34)

[[3 4]
 [1 2]]



---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [101]:
# Exercise 35
a35 = np.array([1, 2, 3])
column_vector = a35.reshape(-1, 1)
print(column_vector)

[[1]
 [2]
 [3]]



---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [103]:
# Exercise 36
a36 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
det = np.linalg.det(a36)
print("Determinant:", det)

Determinant: 0.9999999999999987



---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [105]:
# Exercise 37
a37 = np.array([[2, 0], [0, 3]])
eigenvalues, eigenvectors = np.linalg.eig(a37)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]



---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [107]:
# Exercise 38
# 2x + y = 5, 4x + 3y = 11
A = np.array([[2, 1], [4, 3]])
B = np.array([5, 11])
solution = np.linalg.solve(A, B)
print("Solution:", solution)

Solution: [2. 1.]



---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [109]:
# Exercise 39
a39 = np.array([10, 20, 30])
noise = np.random.normal(0, 1, a39.shape)
noisy_array = a39 + noise
print(noisy_array)

[ 9.34025512 19.60684724 30.05830829]



---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [111]:
# Exercise 40
a40 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
diagonal = np.diag(a40)
print(diagonal)

[ 1  6 11 16]



---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [115]:
import numpy as np
from scipy.spatial.distance import pdist, squareform

In [119]:
# Exercise 41
a41 = np.random.randint(0, 100, 100)
clipped = np.clip(a41, 10, 50)
print(clipped)

[50 50 15 10 31 50 21 50 15 10 27 45 38 50 50 10 28 16 31 50 39 24 45 41
 39 50 10 50 10 40 50 22 24 50 50 50 26 50 22 50 17 50 50 50 50 30 33 16
 50 10 32 32 33 21 10 19 17 50 50 21 50 19 10 37 50 50 50 50 50 31 29 42
 50 40 24 24 22 50 25 37 10 10 50 50 50 26 50 10 44 14 17 50 50 50 46 50
 36 21 50 50]



---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [121]:
# Exercise 42
a42 = np.random.randint(-10, 10, (3, 3))
a42[a42 < 0] = 0
print(a42)

[[8 4 0]
 [0 2 0]
 [6 0 0]]



---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [123]:
# Exercise 43
a43 = np.array([1, 2])
b43 = np.array([3, 4])
inner = np.inner(a43, b43)
outer = np.outer(a43, b43)
print("Inner:", inner)
print("Outer:\n", outer)

Inner: 11
Outer:
 [[3 4]
 [6 8]]



---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [125]:
# Exercise 44
points = np.random.rand(4, 2)  # 4 points in 2D
distances = squareform(pdist(points))
print(distances)

[[0.         0.37406908 0.33635789 0.3375074 ]
 [0.37406908 0.         0.53037233 0.38308719]
 [0.33635789 0.53037233 0.         0.66495868]
 [0.3375074  0.38308719 0.66495868 0.        ]]



---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [127]:
# Exercise 45
a45 = np.array([('Alice', 25, 5.5), ('Bob', 30, 6.0)],
               dtype=[('name', 'U10'), ('age', 'i4'), ('height', 'f4')])
print(a45)

[('Alice', 25, 5.5) ('Bob', 30, 6. )]



---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [129]:
# Exercise 46
a46 = np.random.randint(0, 5, (5, 5))
unique, counts = np.unique(a46, return_counts=True)
print("Matrix:\n", a46)
print("Counts:", dict(zip(unique, counts)))

Matrix:
 [[2 3 2 4 2]
 [2 0 2 4 2]
 [0 0 0 3 2]
 [2 3 0 4 4]
 [0 2 0 2 2]]
Counts: {0: 7, 2: 11, 3: 3, 4: 4}



---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [131]:
# Exercise 47
a47 = np.random.rand(3, 3)
a47_mean_subtracted = a47 - a47.mean(axis=1, keepdims=True)
print("\nExercise 47:\n", a47_mean_subtracted)


Exercise 47:
 [[-0.02460089  0.15794924 -0.13334835]
 [ 0.06319414 -0.19183827  0.12864412]
 [-0.06398709  0.42649651 -0.36250943]]



---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [ ]:
# Exercise 48


---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [ ]:
# Exercise 49


---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [ ]:
# Exercise 50


---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [ ]:
# Exercise 51


---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [ ]:
# Exercise 52


---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [ ]:
# Exercise 53


---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [ ]:
# Exercise 54


---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [ ]:
# Exercise 55


---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [ ]:
# Exercise 56


---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [ ]:
# Exercise 57


---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [ ]:
# Exercise 58


---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [ ]:
# Exercise 59


---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [ ]:
# Exercise 60


---